runtime: nodejs10
service: default

basic_scaling:
    max_instances: 3

handlers:
    - url: /.*
      secure: always
      redirect_http_response_code: 301
      script: auto

    - url: /static
      static_dir: public/static

    - url: /_next/static
      static_dir: _next/static

    - url: /favicon.ico
      static_files: public/favicon.ico
      upload: public/favicon.ico
