export default [
    {
        label: 'Первый этаж',
        groups: [
            {
                along: 6,
                across: 4,
                cells: [
                    {
                        type: 'driver',
                        along: 1,
                        across: 2,
                    },
                    {
                        type: 'empty',
                        along: 1,
                        across: 1,
                    },
                    {
                        type: 'empty',
                        along: 1,
                        across: 1,
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 1,
                        status: 'busy',
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 2,
                        status: 'await',
                    },
                    {
                        type: 'empty',
                        along: 1,
                        across: 1,
                    },
                    {
                        type: 'invalid',
                        along: 2,
                        across: 1,
                        number: 3,
                        status: 'busy',
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 4,
                        status: 'await',
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 5,
                        status: 'await',
                    },
                    {
                        type: 'empty',
                        along: 1,
                        across: 1,
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 6,
                        status: 'busy',
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 7,
                        status: 'await',
                    },
                    {
                        type: 'empty',
                        along: 1,
                        across: 1,
                    },
                    {
                        type: 'invalid',
                        along: 2,
                        across: 1,
                        number: 8,
                        status: 'busy',
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 9,
                        status: 'busy',
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 10,
                        status: 'free',
                    },
                    {
                        type: 'empty',
                        along: 1,
                        across: 1,
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 11,
                        status: 'free',
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 12,
                        status: 'await',
                    },
                    {
                        type: 'ladder',
                        along: 1,
                        across: 2,
                    },
                ],
            },
        ],
    },
    {
        label: 'Второй этаж',
        groups: [
            {
                along: 4,
                across: 4,
                cells: [
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 13,
                        status: 'await',
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 14,
                        status: 'await',
                    },
                    {
                        type: 'ladder',
                        along: 1,
                        across: 2,
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 15,
                        status: 'busy',
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 16,
                        status: 'busy',
                    },
                    {
                        type: 'empty',
                        along: 1,
                        across: 1,
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 17,
                        status: 'free',
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 18,
                        status: 'free',
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 19,
                        status: 'free',
                    },
                    {
                        type: 'empty',
                        along: 1,
                        across: 1,
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 20,
                        status: 'free',
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 21,
                        status: 'busy',
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 22,
                        status: 'await',
                    },
                    {
                        type: 'empty',
                        along: 1,
                        across: 1,
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 23,
                        status: 'busy',
                    },
                ],
            },
            {
                along: 1,
                across: 4,
                cells: [
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 24,
                        status: 'await',
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 25,
                        status: 'await',
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 26,
                        status: 'busy',
                    },
                    {
                        type: 'place',
                        along: 1,
                        across: 1,
                        number: 27,
                        status: 'free',
                    },
                ],
            },
        ],
    },
];
